language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
install:
  - yarn
before_script:
script:
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - npm ci
