language: node_js
node_js:
  - "14.15.5"
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
install:
  - yarn
  - npm install -g npm@latest
script:
  echo "npm test temporarily disabled"
  - npm run test

jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - npm ci
        
        
      
